# Copyright (C) Krzysztof Jakubowski <nadult@fastmail.fm>
# This file is part of libfwk. See license.txt for details.

name: Build dependencies

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
    paths:
      - 'dependencies.json'
      - '.github/workflows/build-package*.yml'

jobs:
  build-packages:
    uses: nadult/libfwk/.github/workflows/build-packages.yml@427a632db883b05f
    with:
      libfwk_path: libfwk
      deps_windows: '["mpg123", "libzip"]'
      deps_linux: '["mpg123", "libzip"]'